#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="                                     


sleep 2

# DEGISKENLER by Nodeist
SEI_WALLET=wallet
SEI=seid
SEI_ID=atlantic-1
SEI_PORT=37
SEI_FOLDER=.sei
SEI_FOLDER2=sei-chain
SEI_VER=1.0.6beta
SEI_REPO=https://github.com/sei-protocol/sei-chain
SEI_GENESIS=https://raw.githubusercontent.com/sei-protocol/testnet/master/sei-incentivized-testnet/genesis.json
SEI_ADDRBOOK=https://raw.githubusercontent.com/sei-protocol/testnet/master/sei-incentivized-testnet/addrboook.json
SEI_MIN_GAS=0
SEI_DENOM=usei
SEI_SEEDS=
SEI_PEERS=27238e2f804bf28a14c186a2e0f0ceaae0d2588f@sei-testnet.p2p.brocha.in:26656,619dde94f0bb1dbacb764879ead4d34c3803dc2e@167.71.204.110:26656,8ff4bd654d7b892f33af5a30ada7d8239d6f467b@91.223.3.190:26656,b9fef895d8e23f4f2473d04a3f4e7a6956f90f89@135.181.59.162:26656

sleep 1

echo "export SEI_WALLET=${SEI_WALLET}" >> $HOME/.bash_profile
echo "export SEI=${SEI}" >> $HOME/.bash_profile
echo "export SEI_ID=${SEI_ID}" >> $HOME/.bash_profile
echo "export SEI_PORT=${SEI_PORT}" >> $HOME/.bash_profile
echo "export SEI_FOLDER=${SEI_FOLDER}" >> $HOME/.bash_profile
echo "export SEI_FOLDER2=${SEI_FOLDER2}" >> $HOME/.bash_profile
echo "export SEI_VER=${SEI_VER}" >> $HOME/.bash_profile
echo "export SEI_REPO=${SEI_REPO}" >> $HOME/.bash_profile
echo "export SEI_GENESIS=${SEI_GENESIS}" >> $HOME/.bash_profile
echo "export SEI_PEERS=${SEI_PEERS}" >> $HOME/.bash_profile
echo "export SEI_SEED=${SEI_SEED}" >> $HOME/.bash_profile
echo "export SEI_MIN_GAS=${SEI_MIN_GAS}" >> $HOME/.bash_profile
echo "export SEI_DENOM=${SEI_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $SEI_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " SEI_NODENAME
	echo 'export SEI_NODENAME='$SEI_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$SEI_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$SEI_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$SEI_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$SEI_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $SEI_REPO
cd $SEI_FOLDER2
git checkout $SEI_VER
make install
mv $HOME/go/bin/seid /usr/bin/

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$SEI config chain-id $SEI_ID
$SEI config keyring-backend file
$SEI init $SEI_NODENAME --chain-id $SEI_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $SEI_GENESIS -O $HOME/$SEI_FOLDER/config/genesis.json
wget $SEI_ADDRBOOK -O $HOME/$SEI_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$SEI_SEEDS"
PEERS="$SEI_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$SEI_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$SEI_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$SEI_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$SEI_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$SEI_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:${SEI_PORT}658\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:${SEI_PORT}657\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${SEI_PORT}060\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:${SEI_PORT}656\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":${SEI_PORT}660\"%" $HOME/$SEI_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${SEI_PORT}317\"%; s%^address = \":8080\"%address = \":${SEI_PORT}080\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${SEI_PORT}090\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${SEI_PORT}091\"%" $HOME/$SEI_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:${SEI_PORT}657\"%" $HOME/$SEI_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$SEI_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$SEI_DENOM\"/" $HOME/$SEI_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$SEI_FOLDER/config/config.toml

# RESET by Nodeist
$SEI tendermint unsafe-reset-all --home $HOME/$SEI_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$SEI.service > /dev/null <<EOF
[Unit]
Description=$SEI
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $SEI) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $SEI
sudo systemctl restart $SEI

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -f $SEI\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${SEI_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
