#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="                                     


sleep 2

# DEGISKENLER by Nodeist
ANONE_WALLET=wallet
ANONE=anoned
ANONE_ID=anone-testnet-1
ANONE_PORT=42
ANONE_FOLDER=.anone
ANONE_FOLDER2=anone
ANONE_VER=testnet-1.0.3
ANONE_REPO=https://github.com/notional-labs/anone
ANONE_GENESIS=https://raw.githubusercontent.com/notional-labs/anone/master/networks/testnet-1/genesis.json
ANONE_ADDRBOOK=
ANONE_MIN_GAS=0
ANONE_DENOM=uan1
ANONE_SEEDS=
ANONE_PEERS=3137535a0d6cc552bd44512ac6a11f4a41c3b3e4@rpc1-testnet.nodejumper.io:26656,49a49db05e945fc38b7a1bc00352cafdaef2176c@95.217.121.243:2280,80f0ef5d7c432d2bae99dc8437a9c3db464890cd@65.108.128.139:2280

sleep 1

echo "export ANONE_WALLET=${ANONE_WALLET}" >> $HOME/.bash_profile
echo "export ANONE=${ANONE}" >> $HOME/.bash_profile
echo "export ANONE_ID=${ANONE_ID}" >> $HOME/.bash_profile
echo "export ANONE_PORT=${ANONE_PORT}" >> $HOME/.bash_profile
echo "export ANONE_FOLDER=${ANONE_FOLDER}" >> $HOME/.bash_profile
echo "export ANONE_FOLDER2=${ANONE_FOLDER2}" >> $HOME/.bash_profile
echo "export ANONE_VER=${ANONE_VER}" >> $HOME/.bash_profile
echo "export ANONE_REPO=${ANONE_REPO}" >> $HOME/.bash_profile
echo "export ANONE_GENESIS=${ANONE_GENESIS}" >> $HOME/.bash_profile
echo "export ANONE_PEERS=${ANONE_PEERS}" >> $HOME/.bash_profile
echo "export ANONE_SEED=${ANONE_SEED}" >> $HOME/.bash_profile
echo "export ANONE_MIN_GAS=${ANONE_MIN_GAS}" >> $HOME/.bash_profile
echo "export ANONE_DENOM=${ANONE_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $ANONE_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " ANONE_NODENAME
	echo 'export ANONE_NODENAME='$ANONE_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$ANONE_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$ANONE_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$ANONE_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$ANONE_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $ANONE_REPO
cd $ANONE_FOLDER2
git checkout $ANONE_VER
make install

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$ANONE config chain-id $ANONE_ID
$ANONE config keyring-backend file
$ANONE init $ANONE_NODENAME --chain-id $ANONE_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $ANONE_GENESIS -O $HOME/$ANONE_FOLDER/config/genesis.json
wget $ANONE_ADDRBOOK -O $HOME/$ANONE_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$ANONE_SEEDS"
PEERS="$ANONE_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$ANONE_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$ANONE_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$ANONE_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$ANONE_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$ANONE_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:${ANONE_PORT}658\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:${ANONE_PORT}657\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${ANONE_PORT}060\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:${ANONE_PORT}656\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":${ANONE_PORT}660\"%" $HOME/$ANONE_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${ANONE_PORT}317\"%; s%^address = \":8080\"%address = \":${ANONE_PORT}080\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${ANONE_PORT}090\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${ANONE_PORT}091\"%" $HOME/$ANONE_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:${ANONE_PORT}657\"%" $HOME/$ANONE_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$ANONE_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$ANONE_DENOM\"/" $HOME/$ANONE_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$ANONE_FOLDER/config/config.toml

# SNAPSHOT
SNAP_RPC="http://rpc1-testnet.nodejumper.io:26657"
LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height); \
BLOCK_HEIGHT=$((LATEST_HEIGHT - 2000)); \
TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash)

echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH

sed -i -E "s|^(enable[[:space:]]+=[[:space:]]+).*$|\1true| ; \
s|^(rpc_servers[[:space:]]+=[[:space:]]+).*$|\1\"$SNAP_RPC,$SNAP_RPC\"| ; \
s|^(trust_height[[:space:]]+=[[:space:]]+).*$|\1$BLOCK_HEIGHT| ; \
s|^(trust_hash[[:space:]]+=[[:space:]]+).*$|\1\"$TRUST_HASH\"|" $HOME/$ANONE_FOLDER	/config/config.toml


# RESET by Nodeist
$ANONE tendermint unsafe-reset-all --home $HOME/$ANONE_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$ANONE.service > /dev/null <<EOF
[Unit]
Description=$ANONE
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $ANONE) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $ANONE
sudo systemctl restart $ANONE

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -f $ANONE\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${ANONE_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
