#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="


sleep 2

# DEGISKENLER by Nodeist
NOIS_WALLET=wallet
NOIS=noisd
NOIS_ID=nois-testnet-002
NOIS_PORT=10
NOIS_FOLDER=.noisd
NOIS_FOLDER2=full-node
NOIS_VER=v0.6.0
NOIS_REPO=https://github.com/noislabs/full-node.git
NOIS_GENESIS=https://raw.githubusercontent.com/noislabs/testnets/main/nois-testnet-002/genesis.json
NOIS_ADDRBOOK=
NOIS_MIN_GAS=0
NOIS_DENOM=unois
NOIS_SEEDS=
NOIS_PEERS=a1222dfb8641e0cb55615b75e0122d5695be1f35@node-0.noislabs.com:26656,2df500525826199afc25665ee7cc45ceb86d68d7@node-1.noislabs.com:26656,61be6aa87471196757ea0f7b1d7897e97b4e09c2@node-2.noislabs.com:26656,cf16671c00eec9a9a047a5c6aa8510cb681b64b8@node-3.noislabs.com:26656

sleep 1

echo "export NOIS_WALLET=${NOIS_WALLET}" >> $HOME/.bash_profile
echo "export NOIS=${NOIS}" >> $HOME/.bash_profile
echo "export NOIS_ID=${NOIS_ID}" >> $HOME/.bash_profile
echo "export NOIS_PORT=${NOIS_PORT}" >> $HOME/.bash_profile
echo "export NOIS_FOLDER=${NOIS_FOLDER}" >> $HOME/.bash_profile
echo "export NOIS_FOLDER2=${NOIS_FOLDER2}" >> $HOME/.bash_profile
echo "export NOIS_VER=${NOIS_VER}" >> $HOME/.bash_profile
echo "export NOIS_REPO=${NOIS_REPO}" >> $HOME/.bash_profile
echo "export NOIS_GENESIS=${NOIS_GENESIS}" >> $HOME/.bash_profile
echo "export NOIS_PEERS=${NOIS_PEERS}" >> $HOME/.bash_profile
echo "export NOIS_SEED=${NOIS_SEED}" >> $HOME/.bash_profile
echo "export NOIS_MIN_GAS=${NOIS_MIN_GAS}" >> $HOME/.bash_profile
echo "export NOIS_DENOM=${NOIS_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $NOIS_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " NOIS_NODENAME
	echo 'export NOIS_NODENAME='$NOIS_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$NOIS_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$NOIS_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$NOIS_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$NOIS_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $NOIS_REPO
cd $NOIS_FOLDER2
git checkout $NOIS_VER
make install

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$NOIS config chain-id $NOIS_ID
$NOIS config keyring-backend file
$NOIS init $NOIS_NODENAME --chain-id $NOIS_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $NOIS_GENESIS -O $HOME/$NOIS_FOLDER/config/genesis.json
wget $NOIS_ADDRBOOK -O $HOME/$NOIS_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$NOIS_SEEDS"
PEERS="$NOIS_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$NOIS_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$NOIS_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$NOIS_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$NOIS_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$NOIS_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:${NOIS_PORT}658\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:${NOIS_PORT}657\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${NOIS_PORT}060\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:${NOIS_PORT}656\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":${NOIS_PORT}660\"%" $HOME/$NOIS_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${NOIS_PORT}317\"%; s%^address = \":8080\"%address = \":${NOIS_PORT}080\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${NOIS_PORT}090\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${NOIS_PORT}091\"%" $HOME/$NOIS_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:${NOIS_PORT}657\"%" $HOME/$NOIS_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$NOIS_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$NOIS_DENOM\"/" $HOME/$NOIS_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$NOIS_FOLDER/config/config.toml

# RESET by Nodeist
$NOIS tendermint unsafe-reset-all --home $HOME/$NOIS_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$NOIS.service > /dev/null <<EOF
[Unit]
Description=$NOIS
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $NOIS) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $NOIS
sudo systemctl restart $NOIS

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -fu noisd -o cat\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${NOIS_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
