#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="


sleep 2

# DEGISKENLER by Nodeist
NTRN_WALLET=wallet
NTRN=neutrond
NTRN_ID=quark-1
NTRN_PORT=12
NTRN_FOLDER=.neutrond
NTRN_FOLDER2=neutron
NTRN_VER=v0.1.0
NTRN_REPO=https://github.com/neutron-org/neutron.git
NTRN_GENESIS=https://raw.githubusercontent.com/neutron-org/testnets/main/quark/genesis.json
NTRN_ADDRBOOK=
NTRN_MIN_GAS=0
NTRN_DENOM=untrn
NTRN_SEEDS=e2c07e8e6e808fb36cca0fc580e31216772841df@seed-1.quark.ntrn.info:26656,c89b8316f006075ad6ae37349220dd56796b92fa@tenderseed.ccvalidators.com:29001
NTRN_PEERS=fcde59cbba742b86de260730d54daa60467c91a5@23.109.158.180:26656,5bdc67a5d5219aeda3c743e04fdcd72dcb150ba3@65.109.31.114:2480,3e9656706c94ae8b11596e53656c80cf092abe5d@65.21.250.197:46656,9cb73281f6774e42176905e548c134fc45bbe579@162.55.134.54:26656,27b07238cf2ea76acabd5d84d396d447d72aa01b@65.109.54.15:51656,f10c2cb08f82225a7ef2367709e8ac427d61d1b5@57.128.144.247:26656,20b4f9207cdc9d0310399f848f057621f7251846@222.106.187.13:40006,5019864f233cee00f3a6974d9ccaac65caa83807@162.19.31.150:55256,2144ce0e9e08b2a30c132fbde52101b753df788d@194.163.168.99:26656,b37326e3acd60d4e0ea2e3223d00633605fb4f79@nebula.p2p.org:26656

sleep 1

echo "export NTRN_WALLET=${NTRN_WALLET}" >> $HOME/.bash_profile
echo "export NTRN=${NTRN}" >> $HOME/.bash_profile
echo "export NTRN_ID=${NTRN_ID}" >> $HOME/.bash_profile
echo "export NTRN_PORT=${NTRN_PORT}" >> $HOME/.bash_profile
echo "export NTRN_FOLDER=${NTRN_FOLDER}" >> $HOME/.bash_profile
echo "export NTRN_FOLDER2=${NTRN_FOLDER2}" >> $HOME/.bash_profile
echo "export NTRN_VER=${NTRN_VER}" >> $HOME/.bash_profile
echo "export NTRN_REPO=${NTRN_REPO}" >> $HOME/.bash_profile
echo "export NTRN_GENESIS=${NTRN_GENESIS}" >> $HOME/.bash_profile
echo "export NTRN_PEERS=${NTRN_PEERS}" >> $HOME/.bash_profile
echo "export NTRN_SEED=${NTRN_SEED}" >> $HOME/.bash_profile
echo "export NTRN_MIN_GAS=${NTRN_MIN_GAS}" >> $HOME/.bash_profile
echo "export NTRN_DENOM=${NTRN_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $NTRN_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " NTRN_NODENAME
	echo 'export NTRN_NODENAME='$NTRN_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$NTRN_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$NTRN_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$NTRN_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$NTRN_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $NTRN_REPO
cd $NTRN_FOLDER2
git checkout $NTRN_VER
make install

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$NTRN config chain-id $NTRN_ID
$NTRN config keyring-backend file
$NTRN init $NTRN_NODENAME --chain-id $NTRN_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $NTRN_GENESIS -O $HOME/$NTRN_FOLDER/config/genesis.json
wget $NTRN_ADDRBOOK -O $HOME/$NTRN_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$NTRN_SEEDS"
PEERS="$NTRN_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$NTRN_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="119"
pruning_keep_every="0"
pruning_interval="19"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$NTRN_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$NTRN_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$NTRN_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$NTRN_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:2${NTRN_PORT}8\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:2${NTRN_PORT}7\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${NTRN_PORT}60\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:2${NTRN_PORT}6\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":2${NTRN_PORT}0\"%" $HOME/$NTRN_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${NTRN_PORT}7\"%; s%^address = \":8080\"%address = \":${NTRN_PORT}80\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${NTRN_PORT}90\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${NTRN_PORT}91\"%" $HOME/$NTRN_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:2${NTRN_PORT}7\"%" $HOME/$NTRN_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$NTRN_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0$NTRN_DENOM\"/" $HOME/$NTRN_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$NTRN_FOLDER/config/config.toml

# RESET by Nodeist
$NTRN tendermint unsafe-reset-all --home $HOME/$NTRN_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$NTRN.service > /dev/null <<EOF
[Unit]
Description=$NTRN
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $NTRN) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $NTRN
sudo systemctl restart $NTRN

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -fu neutrond -o cat\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${NTRN_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
