#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="                                     


sleep 2

# DEGISKENLER by Nodeist
GAIA_WALLET=wallet
GAIA=gaiad
GAIA_ID=GAIA
GAIA_PORT=10
GAIA_FOLDER=.gaia
GAIA_FOLDER2=gaia
GAIA_VER=5b47714dd5607993a1a91f2b06a6d92cbb504721
GAIA_REPO=https://github.com/Stride-Labs/gaia.git
GAIA_GENESIS=https://raw.githubusercontent.com/Stride-Labs/testnet/main/poolparty/gaia/gaia_genesis.json
GAIA_ADDRBOOK=
GAIA_MIN_GAS=0
GAIA_DENOM=uatom
GAIA_SEEDS=
GAIA_PEERS=5892701ed528e73739c418631ead085a58b57567@23.88.100.175:46656,7e064f383fa83ae20095957f61c12b8ebf728f35@34.132.243.128:26656,5b1bd3fb081c79b7bdc5c1fd0a3d90928437266a@78.107.234.44:36656,b8948a13a8953f864ff43fa31ede14a21e44efdc@88.208.57.200:26656

sleep 1

echo "export GAIA_WALLET=${GAIA_WALLET}" >> $HOME/.bash_profile
echo "export GAIA=${GAIA}" >> $HOME/.bash_profile
echo "export GAIA_ID=${GAIA_ID}" >> $HOME/.bash_profile
echo "export GAIA_PORT=${GAIA_PORT}" >> $HOME/.bash_profile
echo "export GAIA_FOLDER=${GAIA_FOLDER}" >> $HOME/.bash_profile
echo "export GAIA_FOLDER2=${GAIA_FOLDER2}" >> $HOME/.bash_profile
echo "export GAIA_VER=${GAIA_VER}" >> $HOME/.bash_profile
echo "export GAIA_REPO=${GAIA_REPO}" >> $HOME/.bash_profile
echo "export GAIA_GENESIS=${GAIA_GENESIS}" >> $HOME/.bash_profile
echo "export GAIA_PEERS=${GAIA_PEERS}" >> $HOME/.bash_profile
echo "export GAIA_SEED=${GAIA_SEED}" >> $HOME/.bash_profile
echo "export GAIA_MIN_GAS=${GAIA_MIN_GAS}" >> $HOME/.bash_profile
echo "export GAIA_DENOM=${GAIA_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $GAIA_NODENAME ]; then
  read -p "NODE ISMI YAZINIZ: " GAIA_NODENAME
  echo 'export GAIA_NODENAME='$GAIA_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$GAIA_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$GAIA_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$GAIA_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$GAIA_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $GAIA_REPO
cd $GAIA_FOLDER2
git checkout $GAIA_VER
make build
sudo cp $HOME/gaia/build/gaiad /usr/local/bin


sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$GAIA config chain-id $GAIA_ID
$GAIA config keyring-backend file
$GAIA init $GAIA_NODENAME --chain-id $GAIA_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $GAIA_GENESIS -O $HOME/$GAIA_FOLDER/config/genesis.json
wget $GAIA_ADDRBOOK -O $HOME/$GAIA_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$GAIA_SEEDS"
PEERS="$GAIA_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$GAIA_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$GAIA_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$GAIA_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$GAIA_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$GAIA_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:${GAIA_PORT}658\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:${GAIA_PORT}657\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${GAIA_PORT}060\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:${GAIA_PORT}656\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":${GAIA_PORT}660\"%" $HOME/$GAIA_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${GAIA_PORT}317\"%; s%^address = \":8080\"%address = \":${GAIA_PORT}080\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${GAIA_PORT}090\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${GAIA_PORT}091\"%" $HOME/$GAIA_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:${GAIA_PORT}657\"%" $HOME/$GAIA_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$GAIA_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$GAIA_DENOM\"/" $HOME/$GAIA_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$GAIA_FOLDER/config/config.toml

# RESET by Nodeist
$GAIA tendermint unsafe-reset-all --home $HOME/$GAIA_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$GAIA.service > /dev/null <<EOF
[Unit]
Description=$GAIA
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $GAIA) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $GAIA
sudo systemctl restart $GAIA

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -fu gaiad -o cat\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${GAIA_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
