#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="                                     


sleep 2

# DEGISKENLER by Nodeist
RBS_WALLET=wallet
RBS=rebusd
RBS_ID=reb_3333-1
RBS_PORT=38
RBS_FOLDER=.rebusd
RBS_FOLDER2=rebus.core
RBS_VER=testnet
RBS_REPO=https://github.com/rebuschain/rebus.core.git
RBS_GENESIS=https://raw.githubusercontent.com/rebuschain/rebus.testnet/master/rebus_3333-1/genesis.json
RBS_ADDRBOOK=
RBS_MIN_GAS=0
RBS_DENOM=arebus
RBS_SEEDS=
RBS_PEERS=c2368a4db640aa26fb8d5bc9d0f331758d42ca86@141.95.65.26:28656,82fc54cd4f7cbb44ee5e9d0565d40b5b29475974@88.198.242.163:46656,718ad850db016002fd628f62cf2b9edf68138db3@143.198.159.196:26656,1f40e130d2c21a32b0d678eabddc45ec3d6964a2@138.201.127.91:26674,eb47d2414351c010c8f747701f184cf3f8a30181@79.143.179.196:16656,64f998cfa053619f1c755fdb6b7e431ae7c0c7b3@95.217.89.23:30530,d5c87b9a13a3d5be1456e9d982c1fc0fe71d8723@38.242.156.72:26656,bcf1b8d1896031da70f5bd1d634d10591d066b1c@5.161.128.219:28656,f084e8960bb714c3446796cb4738e78bc5c3f04b@65.109.18.179:31656

sleep 1

echo "export RBS_WALLET=${RBS_WALLET}" >> $HOME/.bash_profile
echo "export RBS=${RBS}" >> $HOME/.bash_profile
echo "export RBS_ID=${RBS_ID}" >> $HOME/.bash_profile
echo "export RBS_PORT=${RBS_PORT}" >> $HOME/.bash_profile
echo "export RBS_FOLDER=${RBS_FOLDER}" >> $HOME/.bash_profile
echo "export RBS_FOLDER2=${RBS_FOLDER2}" >> $HOME/.bash_profile
echo "export RBS_VER=${RBS_VER}" >> $HOME/.bash_profile
echo "export RBS_REPO=${RBS_REPO}" >> $HOME/.bash_profile
echo "export RBS_GENESIS=${RBS_GENESIS}" >> $HOME/.bash_profile
echo "export RBS_PEERS=${RBS_PEERS}" >> $HOME/.bash_profile
echo "export RBS_SEED=${RBS_SEED}" >> $HOME/.bash_profile
echo "export RBS_MIN_GAS=${RBS_MIN_GAS}" >> $HOME/.bash_profile
echo "export RBS_DENOM=${RBS_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $RBS_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " RBS_NODENAME
	echo 'export RBS_NODENAME='$RBS_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$RBS_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$RBS_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$RBS_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$RBS_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $RBS_REPO
cd $RBS_FOLDER2
git checkout $RBS_VER
make install

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$RBS config chain-id $RBS_ID
$RBS config keyring-backend file
$RBS init $RBS_NODENAME --chain-id $RBS_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $RBS_GENESIS -O $HOME/$RBS_FOLDER/config/genesis.json
wget $RBS_ADDRBOOK -O $HOME/$RBS_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$RBS_SEEDS"
PEERS="$RBS_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$RBS_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$RBS_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$RBS_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$RBS_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$RBS_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:${RBS_PORT}658\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:${RBS_PORT}657\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${RBS_PORT}060\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:${RBS_PORT}656\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":${RBS_PORT}660\"%" $HOME/$RBS_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${RBS_PORT}317\"%; s%^address = \":8080\"%address = \":${RBS_PORT}080\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${RBS_PORT}090\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${RBS_PORT}091\"%" $HOME/$RBS_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:${RBS_PORT}657\"%" $HOME/$RBS_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$RBS_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$RBS_DENOM\"/" $HOME/$RBS_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$RBS_FOLDER/config/config.toml


# RESET by Nodeist
$RBS tendermint unsafe-reset-all --home $HOME/$RBS_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$RBS.service > /dev/null <<EOF
[Unit]
Description=$RBS
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $RBS) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $RBS
sudo systemctl restart $RBS

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -fU rebusd -o cat\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${RBS_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
