#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="


sleep 2

# DEGISKENLER by Nodeist
MND_WALLET=wallet
MND=mande-chaind
MND_ID=mande-testnet-1
MND_PORT=46
MND_FOLDER=.mande-chain
MND_FOLDER2=
MND_VER=
MND_REPO=
MND_GENESIS=https://raw.githubusercontent.com/mande-labs/testnet-1/main/genesis.json
MND_ADDRBOOK=
MND_MIN_GAS=0
MND_DENOM=mand
MND_SEEDS=cd3e4f5b7f5680bbd86a96b38bc122aa46668399@34.171.132.212:26656
MND_PEERS=cd3e4f5b7f5680bbd86a96b38bc122aa46668399@34.171.132.212:26656,6780b2648bd2eb6adca2ca92a03a25b216d4f36b@34.170.16.69:26656,a3e3e20528604b26b792055be84e3fd4de70533b@38.242.199.93:24656

sleep 1

echo "export MND_WALLET=${MND_WALLET}" >> $HOME/.bash_profile
echo "export MND=${MND}" >> $HOME/.bash_profile
echo "export MND_ID=${MND_ID}" >> $HOME/.bash_profile
echo "export MND_PORT=${MND_PORT}" >> $HOME/.bash_profile
echo "export MND_FOLDER=${MND_FOLDER}" >> $HOME/.bash_profile
echo "export MND_FOLDER2=${MND_FOLDER2}" >> $HOME/.bash_profile
echo "export MND_VER=${MND_VER}" >> $HOME/.bash_profile
echo "export MND_REPO=${MND_REPO}" >> $HOME/.bash_profile
echo "export MND_GENESIS=${MND_GENESIS}" >> $HOME/.bash_profile
echo "export MND_PEERS=${MND_PEERS}" >> $HOME/.bash_profile
echo "export MND_SEED=${MND_SEED}" >> $HOME/.bash_profile
echo "export MND_MIN_GAS=${MND_MIN_GAS}" >> $HOME/.bash_profile
echo "export MND_DENOM=${MND_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $MND_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " MND_NODENAME
	echo 'export MND_NODENAME='$MND_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$MND_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$MND_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$MND_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$MND_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd ~
curl -OL https://github.com/mande-labs/testnet-1/raw/main/mande-chaind
mv mande-chaind /$HOME/go/bin/
chmod 744 /$HOME/go/bin/mande-chaind

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$MND config chain-id $MND_ID
$MND config keyring-backend file
$MND init $MND_NODENAME --chain-id $MND_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $MND_GENESIS -O $HOME/$MND_FOLDER/config/genesis.json
wget $MND_ADDRBOOK -O $HOME/$MND_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$MND_SEEDS"
PEERS="$MND_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$MND_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$MND_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$MND_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$MND_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$MND_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:2${MND_PORT}8\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:2${MND_PORT}7\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${MND_PORT}60\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:2${MND_PORT}6\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":2${MND_PORT}0\"%" $HOME/$MND_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${MND_PORT}7\"%; s%^address = \":8080\"%address = \":${MND_PORT}80\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${MND_PORT}90\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${MND_PORT}91\"%" $HOME/$MND_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:2${MND_PORT}7\"%" $HOME/$MND_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$MND_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$MND_DENOM\"/" $HOME/$MND_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$MND_FOLDER/config/config.toml

# RESET by Nodeist
$MND tendermint unsafe-reset-all --home $HOME/$MND_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$MND.service > /dev/null <<EOF
[Unit]
Description=$MND
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $MND) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $MND
sudo systemctl restart $MND

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -fu mande-chaind -o cat\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${MND_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
