#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="


sleep 1

# DEGISKENLER by Nodeist
JKL_WALLET=wallet
JKL=canined
JKL_ID=jackal-1
JKL_PORT=50
JKL_FOLDER=.canine
JKL_FOLDER2=canine-chain
JKL_VER=v1.1.0
JKL_REPO=https://github.com/JackalLabs/canine-chain
JKL_GENESIS=https://raw.githubusercontent.com/JackalLabs/canine-mainnet-genesis/main/genesis/genesis.json
JKL_ADDRBOOK=
JKL_MIN_GAS=0
JKL_DENOM=ujkl
JKL_SEEDS=
JKL_PEERS=c98028a169aabe5f8555090e6cd3370308b391b3@135.181.20.44:2506,ec38fb158ffb0272c4b7c951fc790a8f9849e280@198.244.212.27:26656,399068f8371dce4ae5d7cd7da2c965e765e68f4b@65.108.238.102:17556,39b55b1c49ad0994bbead006be40d9c84b0bf2d4@78.107.253.133:28656,f90a64a0a3f3c0480360e0fe5dd0f806d7741558@207.244.127.5:26656,57d82676ab660e8e4471664d7fee18e3e2e3dd19@89.58.38.59:26656,8be44995ab4eeafcde6e0a9e196c40d483ef6d2a@51.81.155.97:10556


sleep 1

echo "export JKL_WALLET=${JKL_WALLET}" >> $HOME/.bash_profile
echo "export JKL=${JKL}" >> $HOME/.bash_profile
echo "export JKL_ID=${JKL_ID}" >> $HOME/.bash_profile
echo "export JKL_PORT=${JKL_PORT}" >> $HOME/.bash_profile
echo "export JKL_FOLDER=${JKL_FOLDER}" >> $HOME/.bash_profile
echo "export JKL_FOLDER2=${JKL_FOLDER2}" >> $HOME/.bash_profile
echo "export JKL_VER=${JKL_VER}" >> $HOME/.bash_profile
echo "export JKL_REPO=${JKL_REPO}" >> $HOME/.bash_profile
echo "export JKL_GENESIS=${JKL_GENESIS}" >> $HOME/.bash_profile
echo "export JKL_PEERS=${JKL_PEERS}" >> $HOME/.bash_profile
echo "export JKL_SEED=${JKL_SEED}" >> $HOME/.bash_profile
echo "export JKL_MIN_GAS=${JKL_MIN_GAS}" >> $HOME/.bash_profile
echo "export JKL_DENOM=${JKL_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $JKL_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " JKL_NODENAME
	echo 'export JKL_NODENAME='$JKL_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$JKL_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$JKL_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$JKL_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$JKL_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $JKL_REPO
cd $JKL_FOLDER2
git checkout $JKL_VER
make install

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$JKL config chain-id $JKL_ID
$JKL config keyring-backend file
$JKL init $JKL_NODENAME --chain-id $JKL_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $JKL_GENESIS -O $HOME/$JKL_FOLDER/config/genesis.json
wget $JKL_ADDRBOOK -O $HOME/$JKL_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$JKL_SEEDS"
PEERS="$JKL_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$JKL_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$JKL_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$JKL_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$JKL_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$JKL_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:2${JKL_PORT}8\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:2${JKL_PORT}7\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${JKL_PORT}60\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:2${JKL_PORT}6\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":2${JKL_PORT}0\"%" $HOME/$JKL_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${JKL_PORT}7\"%; s%^address = \":8080\"%address = \":${JKL_PORT}80\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${JKL_PORT}90\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${JKL_PORT}91\"%" $HOME/$JKL_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:2${JKL_PORT}7\"%" $HOME/$JKL_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$JKL_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$JKL_DENOM\"/" $HOME/$JKL_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$JKL_FOLDER/config/config.toml

# RESET by Nodeist
$JKL tendermint unsafe-reset-all --home $HOME/$JKL_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$JKL.service > /dev/null <<EOF
[Unit]
Description=$JKL
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $JKL) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $JKL
sudo systemctl restart $JKL

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -fu canined -o cat\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${JKL_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
