#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="                                     


sleep 2

# DEGISKENLER by Nodeist
TIA_WALLET=wallet
TIA=celestia-appd
TIA_ID=mamaki
TIA_PORT=30
TIA_FOLDER=.celestia-app
TIA_FOLDER2=celestia-app
TIA_VER=v0.6.0
TIA_REPO=https://github.com/celestiaorg/celestia-app.git
TIA_GENESIS=https://raw.githubusercontent.com/celestiaorg/networks/master/mamaki/genesis.json
TIA_ADDRBOOK=
TIA_MIN_GAS=0
TIA_DENOM=utia
TIA_SEEDS=
TIA_PEERS=d0b19e4d133441fd41b4d74ac8de2138313ad49e@195.201.41.137:26656,6c076056fc80a813b26e24ba8d28fa374cd72777@149.102.153.197:26656,f7b68a491bae4b10dbab09bb3a875781a01274a5@65.108.199.79:20356,853a9fbb633aed7b6a8c759ba99d1a7674b706a3@38.242.216.151:26656,42b331adaa9ece4c455b92f0d26e3382e46d43f0@161.97.180.20:36656,180378bab87c9cecea544eb406fcd8fcd2cbc21b@168.119.122.78:26656

sleep 1

echo "export TIA_WALLET=${TIA_WALLET}" >> $HOME/.bash_profile
echo "export TIA=${TIA}" >> $HOME/.bash_profile
echo "export TIA_ID=${TIA_ID}" >> $HOME/.bash_profile
echo "export TIA_PORT=${TIA_PORT}" >> $HOME/.bash_profile
echo "export TIA_FOLDER=${TIA_FOLDER}" >> $HOME/.bash_profile
echo "export TIA_FOLDER2=${TIA_FOLDER2}" >> $HOME/.bash_profile
echo "export TIA_VER=${TIA_VER}" >> $HOME/.bash_profile
echo "export TIA_REPO=${TIA_REPO}" >> $HOME/.bash_profile
echo "export TIA_GENESIS=${TIA_GENESIS}" >> $HOME/.bash_profile
echo "export TIA_PEERS=${TIA_PEERS}" >> $HOME/.bash_profile
echo "export TIA_SEED=${TIA_SEED}" >> $HOME/.bash_profile
echo "export TIA_MIN_GAS=${TIA_MIN_GAS}" >> $HOME/.bash_profile
echo "export TIA_MIN_GAS=${TIA_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $TIA_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " TIA_NODENAME
	echo 'export TIA_NODENAME='$TIA_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$TIA_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$TIA_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$TIA_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$TIA_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $TIA_REPO
cd $TIA_FOLDER2
git checkout $TIA_VER
make install

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$TIA config chain-id $TIA_ID
$TIA config keyring-backend file
$TIA init $TIA_NODENAME --chain-id $TIA_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $TIA_GENESIS -O $HOME/$TIA_FOLDER/config/genesis.json
wget $TIA_ADDRBOOK -O $HOME/$TIA_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$TIA_SEEDS"
PEERS="$TIA_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$TIA_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$TIA_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$TIA_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$TIA_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$TIA_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:${TIA_PORT}658\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:${TIA_PORT}657\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${TIA_PORT}060\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:${TIA_PORT}656\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":${TIA_PORT}660\"%" $HOME/$TIA_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${TIA_PORT}317\"%; s%^address = \":8080\"%address = \":${TIA_PORT}080\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${TIA_PORT}090\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${TIA_PORT}091\"%" $HOME/$TIA_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:${TIA_PORT}657\"%" $HOME/$TIA_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$TIA_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$TIA_DENOM\"/" $HOME/$TIA_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$TIA_FOLDER/config/config.toml

# RESET by Nodeist
$TIA tendermint unsafe-reset-all --home $HOME/$TIA_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$TIA.service > /dev/null <<EOF
[Unit]
Description=$TIA
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $TIA) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $TIA
sudo systemctl restart $TIA

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -f $TIA\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${TIA_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
