#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="


sleep 1

# DEGISKENLER by Nodeist
JOE_WALLET=wallet
JOE=joed
JOE_ID=joe-1
JOE_PORT=104
JOE_FOLDER=.joed
JOE_FOLDER2=joe
JOE_VER=main
JOE_REPO=https://github.com/joe-chain/joe
JOE_GENESIS=https://snapshots.polkachu.com/genesis/joe/genesis.json
JOE_ADDRBOOK=
JOE_MIN_GAS=0
JOE_DENOM=ujoe
JOE_SEEDS=ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:18356
JOE_PEERS=

sleep 1

echo "export JOE_WALLET=${JOE_WALLET}" >> $HOME/.bash_profile
echo "export JOE=${JOE}" >> $HOME/.bash_profile
echo "export JOE_ID=${JOE_ID}" >> $HOME/.bash_profile
echo "export JOE_PORT=${JOE_PORT}" >> $HOME/.bash_profile
echo "export JOE_FOLDER=${JOE_FOLDER}" >> $HOME/.bash_profile
echo "export JOE_FOLDER2=${JOE_FOLDER2}" >> $HOME/.bash_profile
echo "export JOE_VER=${JOE_VER}" >> $HOME/.bash_profile
echo "export JOE_REPO=${JOE_REPO}" >> $HOME/.bash_profile
echo "export JOE_GENESIS=${JOE_GENESIS}" >> $HOME/.bash_profile
echo "export JOE_PEERS=${JOE_PEERS}" >> $HOME/.bash_profile
echo "export JOE_SEED=${JOE_SEED}" >> $HOME/.bash_profile
echo "export JOE_MIN_GAS=${JOE_MIN_GAS}" >> $HOME/.bash_profile
echo "export JOE_DENOM=${JOE_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $JOE_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " JOE_NODENAME
	echo 'export JOE_NODENAME='$JOE_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$JOE_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$JOE_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$JOE_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$JOE_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $JOE_REPO
cd $JOE_FOLDER2
git checkout $JOE_VER
make install

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$JOE config chain-id $JOE_ID
$JOE config keyring-backend file
$JOE init $JOE_NODENAME --chain-id $JOE_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $JOE_GENESIS -O $HOME/$JOE_FOLDER/config/genesis.json
wget $JOE_ADDRBOOK -O $HOME/$JOE_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$JOE_SEEDS"
PEERS="$JOE_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$JOE_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$JOE_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$JOE_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$JOE_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$JOE_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:2${JOE_PORT}8\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:2${JOE_PORT}7\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${JOE_PORT}60\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:2${JOE_PORT}6\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":2${JOE_PORT}0\"%" $HOME/$JOE_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${JOE_PORT}7\"%; s%^address = \":8080\"%address = \":${JOE_PORT}80\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${JOE_PORT}90\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${JOE_PORT}91\"%" $HOME/$JOE_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:2${JOE_PORT}7\"%" $HOME/$JOE_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$JOE_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0$JOE_DENOM\"/" $HOME/$JOE_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$JOE_FOLDER/config/config.toml

# RESET by Nodeist
$JOE tendermint unsafe-reset-all --home $HOME/$JOE_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$JOE.service > /dev/null <<EOF
[Unit]
Description=$JOE
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $JOE) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $JOE
sudo systemctl restart $JOE

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -fu joed -o cat\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${JOE_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
