#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="                                     


sleep 2

# DEGISKENLER by Nodeist
CLAN_WALLET=wallet
CLAN=cland
CLAN_ID=playstation-2
CLAN_PORT=31
CLAN_FOLDER=.clan
CLAN_FOLDER2=clan-network
CLAN_VER=v1.0.4-alpha
CLAN_REPO=https://github.com/ClanNetwork/clan-network
CLAN_GENESIS=https://raw.githubusercontent.com/ClanNetwork/testnets/main/playstation-2/genesis.json
CLAN_ADDRBOOK=
CLAN_MIN_GAS=0
CLAN_DENOM=uclan
CLAN_SEEDS=
CLAN_PEERS=be8f9c8ff85674de396075434862d31230adefa4@35.231.178.87:26656,0cb936b2e3256c8d9d90362f2695688b9d3a1b9e@34.73.151.40:26656,e85dc5ec5b77e86265b5b731d4c555ef2430472a@23.88.43.130:26656,9d7ec4cb534717bfa51cdb1136875d17d10f93c3@116.203.60.243:26656,3049356ee6e6d7b2fa5eef03555a620f6ff7591b@65.108.98.218:56656,61db9dede0dff74af9309695b190b556a4266ebf@34.76.96.82:26656,d97c9ac4a8bb0744c7e7c1a17ac77e9c33dc6c34@34.116.229.135:26656


sleep 1

echo "export CLAN_WALLET=${CLAN_WALLET}" >> $HOME/.bash_profile
echo "export CLAN=${CLAN}" >> $HOME/.bash_profile
echo "export CLAN_ID=${CLAN_ID}" >> $HOME/.bash_profile
echo "export CLAN_PORT=${CLAN_PORT}" >> $HOME/.bash_profile
echo "export CLAN_FOLDER=${CLAN_FOLDER}" >> $HOME/.bash_profile
echo "export CLAN_FOLDER2=${CLAN_FOLDER2}" >> $HOME/.bash_profile
echo "export CLAN_VER=${CLAN_VER}" >> $HOME/.bash_profile
echo "export CLAN_REPO=${CLAN_REPO}" >> $HOME/.bash_profile
echo "export CLAN_GENESIS=${CLAN_GENESIS}" >> $HOME/.bash_profile
echo "export CLAN_PEERS=${CLAN_PEERS}" >> $HOME/.bash_profile
echo "export CLAN_SEED=${CLAN_SEED}" >> $HOME/.bash_profile
echo "export CLAN_MIN_GAS=${CLAN_MIN_GAS}" >> $HOME/.bash_profile
echo "export CLAN_DENOM=${CLAN_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $CLAN_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " CLAN_NODENAME
	echo 'export CLAN_NODENAME='$CLAN_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$CLAN_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$CLAN_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$CLAN_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$CLAN_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
git clone https://github.com/ClanNetwork/clan-network && cd clan-network
git checkout v1.0.4-alpha
make install


sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$CLAN config chain-id $CLAN_ID
$CLAN config keyring-backend file
$CLAN init $CLAN_NODENAME --chain-id $CLAN_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $CLAN_GENESIS -O $HOME/$CLAN_FOLDER/config/genesis.json
wget $CLAN_ADDRBOOK -O $HOME/$CLAN_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$CLAN_SEEDS"
PEERS="$CLAN_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$CLAN_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$CLAN_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$CLAN_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$CLAN_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$CLAN_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:${CLAN_PORT}658\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:${CLAN_PORT}657\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${CLAN_PORT}060\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:${CLAN_PORT}656\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":${CLAN_PORT}660\"%" $HOME/$CLAN_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${CLAN_PORT}317\"%; s%^address = \":8080\"%address = \":${CLAN_PORT}080\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${CLAN_PORT}090\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${CLAN_PORT}091\"%" $HOME/$CLAN_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:${CLAN_PORT}657\"%" $HOME/$CLAN_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$CLAN_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$CLAN_DENOM\"/" $HOME/$CLAN_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$CLAN_FOLDER/config/config.toml


# RESET by Nodeist
$CLAN tendermint unsafe-reset-all --home $HOME/$CLAN_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$CLAN.service > /dev/null <<EOF
[Unit]
Description=$CLAN
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $CLAN) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $CLAN
sudo systemctl restart $CLAN

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -f $CLAN\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${CLAN_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
