#!/bin/bash
echo "=================================================="
echo "   _  ______  ___  __________________";
echo "  / |/ / __ \/ _ \/ __/  _/ __/_  __/";
echo " /    / /_/ / // / _/_/ /_\ \  / /   ";
echo "/_/|_/\____/____/___/___/___/ /_/    ";
echo -e "\e[0m"
echo "=================================================="


sleep 2

# DEGISKENLER by Nodeist
OLLO_WALLET=wallet
OLLO=ollod
OLLO_ID=ollo-testnet-0
OLLO_PORT=13
OLLO_FOLDER=.ollo
OLLO_FOLDER2=ollo
OLLO_VER=
OLLO_REPO=https://github.com/OLLO-Station/ollo
OLLO_GENESIS=https://raw.githubusercontent.com/OllO-Station/ollo/master/networks/ollo-testnet-0/genesis.json
OLLO_ADDRBOOK=https://raw.githubusercontent.com/OllO-Station/ollo/master/networks/ollo-testnet-0/addrbook.json
OLLO_MIN_GAS=0
OLLO_DENOM=utia
OLLO_SEEDS=
OLLO_PEERS=06658ccd5c119578fb662633234a2ef154881b94@18.144.61.148


sleep 1

echo "export OLLO_WALLET=${OLLO_WALLET}" >> $HOME/.bash_profile
echo "export OLLO=${OLLO}" >> $HOME/.bash_profile
echo "export OLLO_ID=${OLLO_ID}" >> $HOME/.bash_profile
echo "export OLLO_PORT=${OLLO_PORT}" >> $HOME/.bash_profile
echo "export OLLO_FOLDER=${OLLO_FOLDER}" >> $HOME/.bash_profile
echo "export OLLO_FOLDER2=${OLLO_FOLDER2}" >> $HOME/.bash_profile
echo "export OLLO_VER=${OLLO_VER}" >> $HOME/.bash_profile
echo "export OLLO_REPO=${OLLO_REPO}" >> $HOME/.bash_profile
echo "export OLLO_GENESIS=${OLLO_GENESIS}" >> $HOME/.bash_profile
echo "export OLLO_PEERS=${OLLO_PEERS}" >> $HOME/.bash_profile
echo "export OLLO_SEED=${OLLO_SEED}" >> $HOME/.bash_profile
echo "export OLLO_MIN_GAS=${OLLO_MIN_GAS}" >> $HOME/.bash_profile
echo "export OLLO_DENOM=${OLLO_DENOM}" >> $HOME/.bash_profile
source $HOME/.bash_profile

sleep 1

if [ ! $OLLO_NODENAME ]; then
	read -p "NODE ISMI YAZINIZ: " OLLO_NODENAME
	echo 'export OLLO_NODENAME='$OLLO_NODENAME >> $HOME/.bash_profile
fi

echo -e "NODE ISMINIZ: \e[1m\e[32m$OLLO_NODENAME\e[0m"
echo -e "CUZDAN ISMINIZ: \e[1m\e[32m$OLLO_WALLET\e[0m"
echo -e "CHAIN ISMI: \e[1m\e[32m$OLLO_ID\e[0m"
echo -e "PORT NUMARANIZ: \e[1m\e[32m$OLLO_PORT\e[0m"
echo '================================================='

sleep 2


# GUNCELLEMELER by Nodeist
echo -e "\e[1m\e[32m1. GUNCELLEMELER YUKLENIYOR... \e[0m" && sleep 1
sudo apt update && sudo apt upgrade -y


# GEREKLI PAKETLER by Nodeist
echo -e "\e[1m\e[32m2. GEREKLILIKLER YUKLENIYOR... \e[0m" && sleep 1
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

# GO KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. GO KURULUYOR... \e[0m" && sleep 1
ver="1.18.2"
cd $HOME
wget "https://golang.org/dl/go$ver.linux-amd64.tar.gz"
sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf "go$ver.linux-amd64.tar.gz"
rm "go$ver.linux-amd64.tar.gz"
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile
source ~/.bash_profile
go version

sleep 1

# KUTUPHANE KURULUMU by Nodeist
echo -e "\e[1m\e[32m1. REPO YUKLENIYOR... \e[0m" && sleep 1
cd $HOME
git clone $OLLO_REPO
cd $OLLO_FOLDER2
make install

sleep 1

# KONFIGURASYON by Nodeist
echo -e "\e[1m\e[32m1. KONFIGURASYONLAR AYARLANIYOR... \e[0m" && sleep 1
$OLLO config chain-id $OLLO_ID
$OLLO config keyring-backend file
$OLLO init $OLLO_NODENAME --chain-id $OLLO_ID

# ADDRBOOK ve GENESIS by Nodeist
wget $OLLO_GENESIS -O $HOME/$OLLO_FOLDER/config/genesis.json
wget $OLLO_ADDRBOOK -O $HOME/$OLLO_FOLDER/config/addrbook.json

# EŞLER VE TOHUMLAR by Nodeist
SEEDS="$OLLO_SEEDS"
PEERS="$OLLO_PEERS"
sed -i -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/$OLLO_FOLDER/config/config.toml

sleep 1


# config pruning
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="50"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/$OLLO_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/$OLLO_FOLDER/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/$OLLO_FOLDER/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/$OLLO_FOLDER/config/app.toml


# ÖZELLEŞTİRİLMİŞ PORTLAR by Nodeist
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:${OLLO_PORT}658\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:${OLLO_PORT}657\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:${OLLO_PORT}060\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:${OLLO_PORT}656\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":${OLLO_PORT}660\"%" $HOME/$OLLO_FOLDER/config/config.toml
sed -i.bak -e "s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:${OLLO_PORT}317\"%; s%^address = \":8080\"%address = \":${OLLO_PORT}080\"%; s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:${OLLO_PORT}090\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:${OLLO_PORT}091\"%" $HOME/$OLLO_FOLDER/config/app.toml
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:${OLLO_PORT}657\"%" $HOME/$OLLO_FOLDER/config/client.toml

# PROMETHEUS AKTIVASYON by Nodeist
sed -i -e "s/prometheus = false/prometheus = true/" $HOME/$OLLO_FOLDER/config/config.toml

# MINIMUM GAS AYARI by Nodeist
sed -i -e "s/^minimum-gas-prices *=.*/minimum-gas-prices = \"0.00125$OLLO_DENOM\"/" $HOME/$OLLO_FOLDER/config/app.toml

# INDEXER AYARI by Nodeist
indexer="null" && \
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/$OLLO_FOLDER/config/config.toml

# RESET by Nodeist
$OLLO tendermint unsafe-reset-all --home $HOME/$OLLO_FOLDER

echo -e "\e[1m\e[32m4. SERVIS BASLATILIYOR... \e[0m" && sleep 1
# create service
sudo tee /etc/systemd/system/$OLLO.service > /dev/null <<EOF
[Unit]
Description=$OLLO
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which $OLLO) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF


# SERVISLERI BASLAT by Nodeist
sudo systemctl daemon-reload
sudo systemctl enable $OLLO
sudo systemctl restart $OLLO

echo '=============== KURULUM TAMAM! by Nodeist ==================='
echo -e 'LOGLARI KONTROL ET: \e[1m\e[32mjournalctl -fu ollod -o cat\e[0m'
echo -e "SENKRONIZASYONU KONTROL ET: \e[1m\e[32mcurl -s localhost:${OLLO_PORT}657/status | jq .result.sync_info\e[0m"

source $HOME/.bash_profile
