global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: [localhost:9090]
  - job_name: cosmos
    metrics_path: /metrics
    static_configs: []
  - job_name: node
    metrics_path: /metrics
    static_configs: []
  - job_name: validators
    metrics_path: /metrics/validators
    static_configs: []
  - job_name: validator
    metrics_path: /metrics/validator
    relabel_configs:
      - source_labels: [address]
        target_label: __param_address
    static_configs: []
  - job_name: wallet
    metrics_path: /metrics/wallet
    relabel_configs:
    - source_labels: [address]
      target_label: __param_address
    static_configs: []
